require("plugins.material")
require("plugins.nvm-cmp")
require("plugins.autopairs")
-- require("plugins.bufferline")
require("plugins.telescope")
require("plugins.nvim-commenter")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.colorizer")
require("plugins.dap")
require("plugins.dapui")
require("plugins.harpoon")
require("plugins.lualine")
require("plugins.neodev")

require("mason").setup()
